version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: docs/requirements.txt  # Update path if needed

sphinx:
  configuration: docs/source/conf.py  # Update path if needed
